"""add interaction log table

Revision ID: 5637cb3dd0a8
Revises: a24971f95c63
Create Date: 2026-06-18 10:43:22.899412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5637cb3dd0a8'
down_revision: Union[str, None] = 'a24971f95c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interaction_log_signal', 'interaction_log', ['signal_type'], unique=False)
    op.create_index('idx_interaction_log_user_id', 'interaction_log', ['user_id'], unique=False)
    op.create_index('idx_interaction_log_user_ts', 'interaction_log', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_interaction_log_user_ts', table_name='interaction_log')
    op.drop_index('idx_interaction_log_user_id', table_name='interaction_log')
    op.drop_index('idx_interaction_log_signal', table_name='interaction_log')
    op.drop_table('interaction_log')
    # ### end Alembic commands ###
