"""add_content_catalog_and_user_taste_profiles

Revision ID: a24971f95c63
Revises: 5df056c9ddfd
Create Date: 2026-06-17 21:15:36.412110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a24971f95c63'
down_revision: Union[str, None] = '5df056c9ddfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('genre_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('keyword_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('studio_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('cast_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('crew_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('origin_countries', postgresql.ARRAY(sa.String(length=5)), nullable=True),
    sa.Column('release_era', sa.String(length=20), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('is_seed', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id', 'media_type', name='uq_catalog_tmdb_media')
    )
    op.create_index("ix_catalog_tmdb_id",    "content_catalog", ["tmdb_id"])
    op.create_index("ix_catalog_media_type", "content_catalog", ["media_type"])
    op.create_index("ix_catalog_genre_ids",  "content_catalog", ["genre_ids"], postgresql_using="gin")
    op.create_index("ix_catalog_cast_ids",   "content_catalog", ["cast_ids"], postgresql_using="gin")
    op.create_table('user_taste_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('genre_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cast_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crew_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('era_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('avg_rating_given', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_taste_profiles')
    op.drop_table('content_catalog')
    # ### end Alembic commands ###
