"""add_click_history

Revision ID: 5acc5f2ea44f
Revises: b2c3d4e5f6a7
Create Date: 2026-05-30 11:01:21.678795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acc5f2ea44f'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=10), server_default='movie', nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_click_history_user_clicked', 'click_history', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_click_history_user_id', 'click_history', ['user_id'], unique=False)
    op.drop_index('idx_movies_type', table_name='movies')
    op.drop_index('idx_movies_popularity', table_name='movies')
    op.create_index('idx_movies_popularity', 'movies', ['popularity'], unique=False, postgresql_ops={'popularity': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movies_popularity', table_name='movies', postgresql_ops={'popularity': 'DESC'})
    op.create_index('idx_movies_popularity', 'movies', [sa.text('popularity DESC')], unique=False)
    op.create_index('idx_movies_type', 'movies', ['type'], unique=False)
    op.drop_index('idx_click_history_user_id', table_name='click_history')
    op.drop_index('idx_click_history_user_clicked', table_name='click_history', postgresql_ops={'clicked_at': 'DESC'})
    op.drop_table('click_history')
    # ### end Alembic commands ###
