"""add_news_articles_and_news_movie_links

Revision ID: 266962f591b1
Revises: 5acc5f2ea44f
Create Date: 2026-06-07 20:05:03.432945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '266962f591b1'
down_revision: Union[str, None] = '5acc5f2ea44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('genre_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index('idx_news_fetched_at', 'news_articles', ['fetched_at'], unique=False)
    op.create_index('idx_news_is_archived', 'news_articles', ['is_archived'], unique=False)
    op.create_index('idx_news_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('idx_news_url_hash', 'news_articles', ['url_hash'], unique=False)
    op.create_index('idx_news_view_count', 'news_articles', ['view_count'], unique=False)
    op.create_table('news_movie_links',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'movie_id')
    )
    op.create_index('idx_news_movie_links_movie_id', 'news_movie_links', ['movie_id'], unique=False)
    op.drop_index('idx_click_history_user_clicked', table_name='click_history')
    op.create_index('idx_click_history_user_clicked', 'click_history', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.drop_index('idx_movies_popularity', table_name='movies')
    op.create_index('idx_movies_popularity', 'movies', ['popularity'], unique=False, postgresql_ops={'popularity': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movies_popularity', table_name='movies', postgresql_ops={'popularity': 'DESC'})
    op.create_index('idx_movies_popularity', 'movies', [sa.text('popularity DESC')], unique=False)
    op.drop_index('idx_click_history_user_clicked', table_name='click_history', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_click_history_user_clicked', 'click_history', ['user_id', sa.text('clicked_at DESC')], unique=False)
    op.drop_index('idx_news_movie_links_movie_id', table_name='news_movie_links')
    op.drop_table('news_movie_links')
    op.drop_index('idx_news_view_count', table_name='news_articles')
    op.drop_index('idx_news_url_hash', table_name='news_articles')
    op.drop_index('idx_news_published_at', table_name='news_articles')
    op.drop_index('idx_news_is_archived', table_name='news_articles')
    op.drop_index('idx_news_fetched_at', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
