"""add bio to users

Revision ID: 9d40aa5fc1a9
Revises: db57123c504d
Create Date: 2026-06-22 19:06:15.287260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d40aa5fc1a9'
down_revision: Union[str, None] = 'db57123c504d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_click_history_user_clicked', table_name='click_history')
    op.create_index('idx_click_history_user_clicked', 'click_history', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.drop_index('ix_catalog_cast_ids', table_name='content_catalog', postgresql_using='gin')
    op.drop_index('ix_catalog_genre_ids', table_name='content_catalog', postgresql_using='gin')
    op.drop_index('ix_catalog_media_type', table_name='content_catalog')
    op.drop_index('ix_catalog_tmdb_id', table_name='content_catalog')
    op.alter_column('movie_ratings', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'movie_ratings', 'movies', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_movies_title_trgm', table_name='movies', postgresql_using='gin')
    op.drop_index('idx_movies_popularity', table_name='movies')
    op.create_index('idx_movies_popularity', 'movies', ['popularity'], unique=False, postgresql_ops={'popularity': 'DESC'})
    op.alter_column('notifications', 'seen',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('rating_needed', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('tv_ratings', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'tv_ratings', 'movies', ['id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.drop_constraint('idx_user_tv', 'watching_tracker', type_='unique')
    op.create_index('idx_user_tv', 'watching_tracker', ['user_id', 'tv_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_tv', table_name='watching_tracker')
    op.create_unique_constraint('idx_user_tv', 'watching_tracker', ['user_id', 'tv_id'])
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'tv_ratings', type_='foreignkey')
    op.alter_column('tv_ratings', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('rating_needed', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('notifications', 'seen',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_index('idx_movies_popularity', table_name='movies', postgresql_ops={'popularity': 'DESC'})
    op.create_index('idx_movies_popularity', 'movies', [sa.text('popularity DESC')], unique=False)
    op.create_index('idx_movies_title_trgm', 'movies', [sa.text('lower(title::text)')], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'movie_ratings', type_='foreignkey')
    op.alter_column('movie_ratings', 'fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index('ix_catalog_tmdb_id', 'content_catalog', ['tmdb_id'], unique=False)
    op.create_index('ix_catalog_media_type', 'content_catalog', ['media_type'], unique=False)
    op.create_index('ix_catalog_genre_ids', 'content_catalog', ['genre_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_catalog_cast_ids', 'content_catalog', ['cast_ids'], unique=False, postgresql_using='gin')
    op.drop_index('idx_click_history_user_clicked', table_name='click_history', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_click_history_user_clicked', 'click_history', ['user_id', sa.text('clicked_at DESC')], unique=False)
    # ### end Alembic commands ###
