"""create_all_tables

Revision ID: c2cbd085a5a6
Revises: 
Create Date: 2026-05-26 11:18:59.242757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2cbd085a5a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('profile_path', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=255), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('backdrop_path', sa.Text(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movies_fts', 'movies', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_movies_language', 'movies', ['original_language'], unique=False)
    op.create_index('idx_movies_popularity', 'movies', ['popularity'], unique=False, postgresql_ops={'popularity': 'DESC'})
    op.create_index('idx_movies_release_date', 'movies', ['release_date'], unique=False)
    op.create_index('idx_movies_vote_average', 'movies', ['vote_average'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('movie_directors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'director_id')
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('story_score', sa.Float(), nullable=True),
    sa.Column('acting_score', sa.Float(), nullable=True),
    sa.Column('direction_score', sa.Float(), nullable=True),
    sa.Column('visuals_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('acting_score IS NULL OR (acting_score >= 0 AND acting_score <= 10)', name='chk_acting_score'),
    sa.CheckConstraint('direction_score IS NULL OR (direction_score >= 0 AND direction_score <= 10)', name='chk_direction_score'),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 10', name='chk_overall_score'),
    sa.CheckConstraint('story_score IS NULL OR (story_score >= 0 AND story_score <= 10)', name='chk_story_score'),
    sa.CheckConstraint('visuals_score IS NULL OR (visuals_score >= 0 AND visuals_score <= 10)', name='chk_visuals_score'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_rating_user_movie')
    )
    op.create_index('idx_ratings_movie_id', 'ratings', ['movie_id'], unique=False)
    op.create_index('idx_ratings_overall', 'ratings', ['overall_score'], unique=False)
    op.create_index('idx_ratings_user_id', 'ratings', ['user_id'], unique=False)
    op.create_table('user_genre_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'genre_id')
    )
    op.create_table('watch_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('watch_source', sa.String(length=50), nullable=True),
    sa.Column('rewatched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_watch_user_movie')
    )
    op.create_index('idx_watch_user_id', 'watch_history', ['user_id'], unique=False)
    op.create_index('idx_watch_watched_at', 'watch_history', ['user_id', 'watched_at'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_watchlist_user_movie')
    )
    op.create_index('idx_watchlist_user_id', 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watchlist_user_id', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('idx_watch_watched_at', table_name='watch_history')
    op.drop_index('idx_watch_user_id', table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_table('user_genre_preferences')
    op.drop_index('idx_ratings_user_id', table_name='ratings')
    op.drop_index('idx_ratings_overall', table_name='ratings')
    op.drop_index('idx_ratings_movie_id', table_name='ratings')
    op.drop_table('ratings')
    op.drop_table('movie_genres')
    op.drop_table('movie_directors')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_movies_vote_average', table_name='movies')
    op.drop_index('idx_movies_release_date', table_name='movies')
    op.drop_index('idx_movies_popularity', table_name='movies', postgresql_ops={'popularity': 'DESC'})
    op.drop_index('idx_movies_language', table_name='movies')
    op.drop_index('idx_movies_fts', table_name='movies', postgresql_using='gin')
    op.drop_table('movies')
    op.drop_table('genres')
    op.drop_table('directors')
    # ### end Alembic commands ###
