"""Remove news tables

Revision ID: 46ed982502d7
Revises: 266962f591b1
Create Date: 2026-06-07 20:35:56.285507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ed982502d7'
down_revision: Union[str, None] = '266962f591b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_fetched_at', table_name='news_articles')
    op.drop_index('idx_news_is_archived', table_name='news_articles')
    op.drop_index('idx_news_published_at', table_name='news_articles')
    op.drop_index('idx_news_url_hash', table_name='news_articles')
    op.drop_index('idx_news_view_count', table_name='news_articles')
    op.drop_index('idx_news_movie_links_movie_id', table_name='news_movie_links')
    op.drop_table('news_movie_links')
    op.drop_table('news_articles')
    op.drop_index('idx_click_history_user_clicked', table_name='click_history')
    op.create_index('idx_click_history_user_clicked', 'click_history', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.drop_index('idx_movies_popularity', table_name='movies')
    op.create_index('idx_movies_popularity', 'movies', ['popularity'], unique=False, postgresql_ops={'popularity': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movies_popularity', table_name='movies', postgresql_ops={'popularity': 'DESC'})
    op.create_index('idx_movies_popularity', 'movies', [sa.text('popularity DESC')], unique=False)
    op.drop_index('idx_click_history_user_clicked', table_name='click_history', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_click_history_user_clicked', 'click_history', ['user_id', sa.text('clicked_at DESC')], unique=False)
    op.create_table('news_movie_links',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], name='news_movie_links_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='news_movie_links_movie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'movie_id', name='news_movie_links_pkey')
    )
    op.create_index('idx_news_movie_links_movie_id', 'news_movie_links', ['movie_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('genre_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('url_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='news_articles_pkey'),
    sa.UniqueConstraint('url', name='news_articles_url_key'),
    sa.UniqueConstraint('url_hash', name='news_articles_url_hash_key')
    )
    op.create_index('idx_news_view_count', 'news_articles', ['view_count'], unique=False)
    op.create_index('idx_news_url_hash', 'news_articles', ['url_hash'], unique=False)
    op.create_index('idx_news_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('idx_news_is_archived', 'news_articles', ['is_archived'], unique=False)
    op.create_index('idx_news_fetched_at', 'news_articles', ['fetched_at'], unique=False)
    # ### end Alembic commands ###
