"""add_negative_weights_to_taste_profile

Revision ID: db57123c504d
Revises: 8bb951367160
Create Date: 2026-06-19 22:37:22.808563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db57123c504d'
down_revision: Union[str, None] = '8bb951367160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_taste_profiles', sa.Column('negative_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_taste_profiles', 'negative_weights')
    # ### end Alembic commands ###
